<?php

namespace AppBundle\Repository;

/**
 * OccurrenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurrenceRepository extends \Doctrine\ORM\EntityRepository
{
}
