<?php

namespace AppBundle\Repository;

use AppBundle\Entity\OccurrenceDictionary;
use Doctrine\ORM\EntityRepository;

/**
 * OccurrenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurrenceRepository extends EntityRepository
{
    /**
     * Fetch top occurrence by dictionary
     *
     * @param OccurrenceDictionary $occurrenceDictionary
     * @param int $numberResult
     * @return array
     */
    public function fetchTopOccurrence(OccurrenceDictionary $occurrenceDictionary, $numberResult = 5): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('o')
            ->where('o.dictionary = :occurrence_dictionary')
            ->orderBy('o.value', 'DESC')
            ->setParameter('occurrence_dictionary', $occurrenceDictionary)
            ->setMaxResults($numberResult)
            ->getQuery()
            ->getResult();
    }

    /**
     * Fetch top occurrence by dictionary and letter
     *
     * @param OccurrenceDictionary $occurrenceDictionary
     * @param int $letter
     * @param int $numberResult
     * @return array
     */
    public function fetchTopOccurrenceByDictionaryAndLetter(
        OccurrenceDictionary $occurrenceDictionary,
        int $letter,
        int $numberResult = 5): array
    {
        return $this->createQueryBuilder('o')
            ->where('o.dictionary = :occurrence_dictionary')
            ->andWhere('o.letter = :letter')
            ->orderBy('o.value', 'DESC')
            ->setParameter('occurrence_dictionary', $occurrenceDictionary)
            ->setParameter('letter', $letter)
            ->setMaxResults($numberResult)
            ->getQuery()
            ->getResult();
    }
}
