services:
#    dvc_dictionary_consumer.example:
#        class: Dvc\DictionaryConsumerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    dictionary:
        class: Dvc\DictionaryConsumerBundle\Services\Dictionary
        arguments: ['@guzzle.client.api_dictionary']